# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool: rkagent

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cf8d9530-f460-40b3-bd50-bba420a58d4d'
  imageRepository: 'rkimgv1'
  containerRegistry: 'riteshkuldeep.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: 'v1'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'riteshkuldeep.azurecr.io/rkimg'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'riteshkuldeep.azurecr.io'
        tags: |
          v1

# Optional: If you have another stage, add it here with dependencies if needed
# - stage: NextStage
#   displayName: Next Stage
#   dependsOn: Build
#   jobs:
#   - job: NextJob
#     displayName: Next Job
#     steps:
#       - script: echo "This is the next job after the Build stage."
